apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: mcp-server:local
          imagePullPolicy: IfNotPresent
          env:
            - name: CONFIG_PATH
              value: /app/config/tools.yaml
            - name: AUTH_CONFIG_PATH
              value: /app/config/auth.yaml
            - name: HOST
              value: "0.0.0.0"
            - name: HEALTH_PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "info"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
